/**
 * Nango Client-Side SDK
 * Handles OAuth flows and connection management from the browser
 *
 * SECURITY: Uses session tokens (no public key needed!)
 * Session tokens are generated by your backend and are scoped per user
 */

'use client';

import Nango from '@nangohq/frontend';

/**
 * Nango frontend instance
 * Session tokens are set dynamically per OAuth flow
 */
export const nangoClient = new Nango();

/**
 * Get a session token from the backend
 */
async function getSessionToken(
  allowedIntegrations?: string[],
): Promise<{ success: true; token: string } | { success: false; error: string }> {
  try {
    const response = await fetch('/api/integrations/session-token', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ allowedIntegrations }),
    });

    if (!response.ok) {
      const error = await response.json();
      return { success: false, error: error.error || 'Failed to get session token' };
    }

    const data = await response.json();
    return { success: true, token: data.sessionToken };
  } catch (error) {
    console.error('Failed to get session token:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to get session token',
    };
  }
}

/**
 * Trigger OAuth flow for an integration using Nango's Connect UI
 *
 * This will:
 * 1. Get a session token from your backend
 * 2. Open Nango's Connect UI modal
 * 3. User authorizes the integration
 * 4. Return connection details
 *
 * @param integrationId - The integration to connect (e.g., 'gmail', 'slack')
 * @param onSuccess - Callback when connection succeeds
 * @param onError - Callback when connection fails
 */
export async function connectIntegration(
  integrationId: string,
  callbacks?: {
    onSuccess?: (connectionId: string) => void;
    onError?: (error: string) => void;
    onClose?: () => void;
  },
): Promise<void> {
  try {
    // Open Connect UI
    const connect = nangoClient.openConnectUI({
      onEvent: (event) => {
        if (event.type === 'close') {
          callbacks?.onClose?.();
        } else if (event.type === 'connect') {
          // Connection successful
          const connectionId = event.payload.connectionId;
          callbacks?.onSuccess?.(connectionId);
        }
      },
    });

    // Get session token from backend
    const tokenResult = await getSessionToken([integrationId]);

    if (!tokenResult.success) {
      callbacks?.onError?.(tokenResult.error);
      return;
    }

    // Set session token (this triggers the OAuth flow)
    connect.setSessionToken(tokenResult.token);
  } catch (error) {
    console.error(`OAuth flow failed for ${integrationId}:`, error);
    callbacks?.onError?.(error instanceof Error ? error.message : 'OAuth flow failed');
  }
}

/**
 * Trigger OAuth flow for multiple integrations (user picks one)
 *
 * @param integrationIds - List of integrations user can choose from
 */
export async function connectMultipleIntegrations(
  integrationIds: string[],
  callbacks?: {
    onSuccess?: (connectionId: string, integrationId: string) => void;
    onError?: (error: string) => void;
    onClose?: () => void;
  },
): Promise<void> {
  try {
    const connect = nangoClient.openConnectUI({
      onEvent: (event) => {
        if (event.type === 'close') {
          callbacks?.onClose?.();
        } else if (event.type === 'connect') {
          const connectionId = event.payload.connectionId;
          const integrationId = event.payload.providerConfigKey;
          callbacks?.onSuccess?.(connectionId, integrationId);
        }
      },
    });

    const tokenResult = await getSessionToken(integrationIds);

    if (!tokenResult.success) {
      callbacks?.onError?.(tokenResult.error);
      return;
    }

    connect.setSessionToken(tokenResult.token);
  } catch (error) {
    console.error('OAuth flow failed:', error);
    callbacks?.onError?.(error instanceof Error ? error.message : 'OAuth flow failed');
  }
}

/**
 * Reconnect an existing connection (for expired credentials or scope changes)
 * Uses direct OAuth flow instead of Nango
 */
export async function reconnectIntegration(
  integrationId: string,
  connectionId: string,
  callbacks?: {
    onSuccess?: () => void;
    onError?: (error: string) => void;
    onClose?: () => void;
  },
): Promise<void> {
  try {
    // Get OAuth URL from backend
    const response = await fetch('/api/integrations/reconnect-token', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ integrationType: integrationId }),
    });

    if (!response.ok) {
      const error = await response.json();
      callbacks?.onError?.(error.error || 'Failed to reconnect');
      return;
    }

    const { authUrl } = await response.json();

    // Redirect user to OAuth URL
    window.location.href = authUrl;
  } catch (error) {
    console.error('Reconnect failed:', error);
    callbacks?.onError?.(error instanceof Error ? error.message : 'Reconnect failed');
  }
}
