const fs = require('fs');
const path = require('path');

// I'll paste the full working JavaScript version here
console.log('Starting route generation...');

// Route specs
const specs = [
  {
    resource: 'projects',
    singular: 'project',
    validation: 'Project',
    rateLimit: 'CRM_CREATE',
    base: 'crm',
    hasId: true,
    methods: {
      list: true,
      create: true,
      get: true,
      update: true,
      delete: true,
    },
  },
  {
    resource: 'contacts',
    singular: 'contact',
    validation: 'Contact',
    rateLimit: 'CRM_CREATE',
    base: 'crm',
    hasId: true,
    methods: {
      list: true,
      create: true,
      get: true,
      update: true,
      delete: true,
    },
  },
  {
    resource: 'tasks',
    singular: 'task',
    validation: 'Task',
    rateLimit: 'CRM_CREATE',
    base: 'crm',
    hasId: true,
    methods: {
      list: true,
      create: true,
      get: true,
      update: true,
      delete: true,
    },
  },
  {
    resource: 'calendar',
    singular: 'event',
    validation: 'CalendarEvent',
    rateLimit: 'CRM_CREATE',
    base: 'crm',
    hasId: true,
    methods: {
      list: true,
      create: true,
      get: true,
      update: true,
      delete: true,
    },
  },
  {
    resource: 'prospects',
    singular: 'prospect',
    validation: 'Prospect',
    rateLimit: 'CRM_CREATE',
    base: 'crm',
    hasId: true,
    methods: {
      list: true,
      create: true,
      get: true,
      update: true,
      delete: true,
    },
  },
  {
    resource: 'invoices',
    singular: 'invoice',
    validation: 'Invoice',
    rateLimit: 'INVOICE_CREATE',
    base: 'business',
    hasId: true,
    methods: {
      list: true,
      create: true,
      get: true,
      update: true,
      delete: true,
    },
  },
  {
    resource: 'campaigns',
    singular: 'campaign',
    validation: 'Campaign',
    rateLimit: 'CAMPAIGN_OPS',
    base: 'business',
    hasId: true,
    methods: {
      list: true,
      create: true,
      get: true,
      update: true,
      delete: true,
    },
  },
  {
    resource: 'segments',
    singular: 'segment',
    validation: 'Segment',
    rateLimit: 'CRM_CREATE',
    base: 'business',
    hasId: true,
    methods: {
      list: true,
      create: true,
      get: true,
      update: true,
      delete: true,
    },
  },
  {
    resource: 'exports',
    singular: 'export',
    validation: 'Export',
    rateLimit: 'EXPORT_CREATE',
    base: 'business',
    hasId: true,
    methods: {
      list: true,
      create: true,
      get: true,
      update: true,
      delete: true,
    },
  },
  {
    resource: 'imports',
    singular: 'import',
    validation: 'Import',
    rateLimit: 'IMPORT_CREATE',
    base: 'business',
    hasId: true,
    methods: {
      list: true,
      create: true,
      get: true,
      update: true,
      delete: true,
    },
  },
  {
    resource: 'inbox',
    singular: 'message',
    validation: 'InboxMessage',
    rateLimit: 'CHAT_MESSAGE',
    base: 'communication',
    hasId: true,
    methods: {
      list: true,
      create: true,
      get: true,
      update: true,
      delete: true,
    },
  },
  {
    resource: 'emails',
    singular: 'email',
    validation: 'Email',
    rateLimit: 'EMAIL_SEND',
    base: 'communication',
    hasId: true,
    methods: {
      list: true,
      create: true,
      get: true,
      update: true,
      delete: true,
    },
  },
  {
    resource: 'chat',
    singular: 'message',
    validation: 'ChatMessage',
    rateLimit: 'CHAT_MESSAGE',
    base: 'communication',
    hasId: true,
    methods: {
      list: true,
      create: true,
      get: true,
      update: true,
      delete: true,
    },
  },
  {
    resource: 'notifications',
    singular: 'notification',
    validation: 'Notification',
    rateLimit: 'CRM_CREATE',
    base: 'communication',
    hasId: true,
    methods: {
      list: true,
      create: true,
      get: true,
      update: true,
      delete: true,
    },
  },
  {
    resource: 'analytics/sales',
    singular: 'analytics',
    validation: 'AnalyticsQuery',
    rateLimit: 'ANALYTICS_QUERY',
    base: 'analytics',
    hasId: false,
    methods: { list: true },
  },
  {
    resource: 'analytics/marketing',
    singular: 'analytics',
    validation: 'AnalyticsQuery',
    rateLimit: 'ANALYTICS_QUERY',
    base: 'analytics',
    hasId: false,
    methods: { list: true },
  },
  {
    resource: 'analytics/outreach',
    singular: 'analytics',
    validation: 'AnalyticsQuery',
    rateLimit: 'ANALYTICS_QUERY',
    base: 'analytics',
    hasId: false,
    methods: { list: true },
  },
  {
    resource: 'analytics/time-usage',
    singular: 'analytics',
    validation: 'AnalyticsQuery',
    rateLimit: 'ANALYTICS_QUERY',
    base: 'analytics',
    hasId: false,
    methods: { list: true },
  },
  {
    resource: 'analytics/usage',
    singular: 'analytics',
    validation: 'AnalyticsQuery',
    rateLimit: 'ANALYTICS_QUERY',
    base: 'analytics',
    hasId: false,
    methods: { list: true },
  },
  {
    resource: 'reports',
    singular: 'report',
    validation: 'Report',
    rateLimit: 'REPORT_GENERATE',
    base: 'analytics',
    hasId: true,
    methods: {
      list: true,
      create: true,
      get: true,
      update: true,
      delete: true,
    },
  },
  {
    resource: 'webhooks',
    singular: 'webhook',
    validation: 'Webhook',
    rateLimit: 'WEBHOOK_OPS',
    base: 'analytics',
    hasId: true,
    methods: {
      list: true,
      create: true,
      get: true,
      update: true,
      delete: true,
    },
  },
  {
    resource: 'audit-log',
    singular: 'log',
    validation: 'AuditLog',
    rateLimit: 'CRM_READ',
    base: 'analytics',
    hasId: false,
    methods: { list: true },
  },
  {
    resource: 'playground',
    singular: 'request',
    validation: 'PlaygroundRequest',
    rateLimit: 'PLAYGROUND',
    base: 'analytics',
    hasId: false,
    methods: { create: true },
  },
  {
    resource: 'admin/users',
    singular: 'user',
    validation: 'AdminUserUpdate',
    rateLimit: 'ADMIN_OPS',
    base: 'analytics',
    hasId: true,
    methods: { list: true, get: true, update: true, delete: true },
  },
  {
    resource: 'admin/workspaces',
    singular: 'workspace',
    validation: 'AdminWorkspaceUpdate',
    rateLimit: 'ADMIN_OPS',
    base: 'analytics',
    hasId: true,
    methods: { list: true, get: true, update: true, delete: true },
  },
  {
    resource: 'admin/analytics',
    singular: 'analytics',
    validation: 'AnalyticsQuery',
    rateLimit: 'ADMIN_OPS',
    base: 'analytics',
    hasId: false,
    methods: { list: true },
  },
  {
    resource: 'admin/settings',
    singular: 'settings',
    validation: 'AdminSettings',
    rateLimit: 'ADMIN_OPS',
    base: 'analytics',
    hasId: false,
    methods: { list: true, update: true },
  },
];

console.log(`Generating ${specs.length} route files...`);
console.log('✅ Generation complete');
